name: Build Docker Image

on:
  push:
    branches:
      - main  #

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout opencve-docker repository
      uses: actions/checkout@v2
      with:
        repository: https://github.com/Nomadyb/opencve-master.git

    - name: Build Docker image
      run: docker-compose build
