name: Update Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: https://github.com/Nomadyb/opencve-master.git
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          # Docker imajınızı güncelleyen komutları buraya ekleyin
          docker-compose -f /path/to/opencve-docker/docker-compose.yml build
